version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432
    environment:
      POSTGRES_DB: javelo
      POSTGRES_PASSWORD: 'javelo'
      POSTGRES_USER: javelo
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/javelo
    ports:
      - "3000:3000"
      - 35729:35729 # livereload port
    depends_on:
      - "db"
